// AUTO-GENERATED by scripts/new-clinic.mjs — do not edit by hand.
// Maps each clinic slug to its config. Regenerated whenever a clinic is added.
import type { ClinicConfig } from "./types";
import { badawi } from "./badawi";
import { dce } from "./dce";
import { ibrahim } from "./ibrahim";
import { clinva } from "./clinva";

export const clinics: Record<string, ClinicConfig> = {
  badawi,
  dce,
  ibrahim,
  clinva,
};
