#!/usr/bin/env node
/**
 * new-clinic — scaffold a brand-new clinic (a new "account").
 *
 * It creates:
 *   1. src/lib/clinics/<slug>.ts        — the typed ClinicConfig (branding)
 *   2. regenerates registry.generated.ts (registers the new clinic)
 *   3. clinics/<slug>/.env              — per-clinic env (own DB + secrets)
 *   4. clinics/<slug>/assets/           — drop the hero photo / logo here
 *   5. clinics/<slug>/DEPLOY.md         — how to run/deploy this clinic
 *
 * After this, `node scripts/export-clinic.mjs <slug>` produces a standalone
 * deployable app folder in deploy/<slug>/.
 *
 * Usage (flags or interactive):
 *   node scripts/new-clinic.mjs --slug=sara --brand-en="Dr. Sara" --brand-ar="د. سارة" \
 *     --name-en="Dr. Sara Ali" --name-ar="د. سارة علي" --role-en="Cosmetic Dentist" \
 *     --role-ar="طبيبة تجميل الأسنان" --whatsapp=201000000000 --phone="+20 100 000 0000" \
 *     --email=info@drsara.clinic --city="Cairo" --photo=doctor-sara.png
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import readline from "node:readline";

const ROOT = process.cwd();
const CLINICS_SRC = path.join(ROOT, "src", "lib", "clinics");

function parseArgs(argv) {
  const out = {};
  for (const a of argv) {
    const m = /^--([^=]+)=(.*)$/.exec(a);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

function ask(rl, q, def = "") {
  return new Promise((res) => rl.question(`${q}${def ? ` [${def}]` : ""}: `, (a) => res((a || def).trim())));
}

const slugify = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
const esc = (s) => String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
const secret = (n = 48) => crypto.randomBytes(n).toString("base64").replace(/[^a-zA-Z0-9]/g, "").slice(0, n);

function configTemplate(c) {
  const bi = (o) => `{ en: "${esc(o.en)}", ar: "${esc(o.ar)}" }`;
  return `import type { ClinicConfig } from "./types";

/** ${esc(c.nameEn)} — generated by scripts/new-clinic.mjs. */
export const ${c.slug}: ClinicConfig = {
  slug: "${c.slug}",
  brand: ${bi(c.brand)},
  doctorName: ${bi(c.name)},
  role: ${bi(c.role)},

  hero: {
    badge: ${bi(c.badge)},
    title1: { en: "Craft Your Perfect Smile with", ar: "اصنع ابتسامتك المثالية مع" },
    title2: ${bi(c.role)},
    subtitle: ${bi(c.subtitle)},
    photo: "${esc(c.photo)}",
  },

  about: {
    role: ${bi(c.role)},
    bio1: ${bi(c.bio1)},
    bio2: {
      en: "Combining modern, fully-sterilized facilities with a gentle touch for pain-free treatment and natural-looking results in a calm, welcoming environment.",
      ar: "نجمع بين التجهيزات الحديثة المعقّمة بالكامل واللمسة اللطيفة لعلاج خالٍ من الألم ونتائج طبيعية في بيئة هادئة ومريحة.",
    },
    point1: { en: "Cosmetic & smile-design expert", ar: "خبير تجميل وتصميم الابتسامة" },
    point2: { en: "Pain-free, modern techniques", ar: "تقنيات حديثة بلا ألم" },
    point3: { en: "Fully sterilized, modern clinic", ar: "عيادة حديثة ومعقّمة بالكامل" },
  },

  team: [
    { name: ${bi(c.name)}, role: ${bi(c.role)}, photo: "${esc(c.photo)}" },
  ],

  gallery: {
    style: "slider",
    headline: { en: "Drag to See the Difference", ar: "اسحب لترى الفرق" },
    subtitle: {
      en: "Slide the handle to reveal real before-and-after results from our clinic.",
      ar: "حرّك المؤشر لتكشف نتائج حقيقية قبل وبعد العلاج في عيادتنا.",
    },
    cases: [
      { before: "/cases/before-1.png", after: "/cases/after-1.png", title: { en: "Smile Makeover", ar: "تجميل الابتسامة" }, tag: { en: "Cosmetic", ar: "تجميلي" } },
      { before: "/cases/before-2.png", after: "/cases/after-2.png", title: { en: "Full Restoration", ar: "ترميم كامل" }, tag: { en: "Restoration", ar: "ترميم" } },
    ],
  },

  theme: {
    primary: "${c.primary}",
    primaryDark: "${c.primaryDark}",
    accent: "${c.accent}",
    background: "#f7f5f1",
    surface: "#ffffff",
    surface2: "#f1ece3",
  },

  contact: {
    phone: "${esc(c.phone)}",
    phoneDisplay: "${esc(c.phone)}",
    whatsapp: "${esc(c.whatsapp)}",
    email: "${esc(c.email)}",
    address: { street: "", locality: "${esc(c.city)}", region: "${esc(c.city)}", country: "EG", postalCode: "" },
    addressDisplay: { en: "${esc(c.city)}, Egypt", ar: "${esc(c.city)}، مصر" },
    hours: { en: "Open daily — call to book your visit", ar: "مفتوح يوميًا — اتصل لحجز موعدك" },
    geo: { lat: 30.0444, lng: 31.2357 },
    mapQuery: "${esc(c.nameEn)} ${esc(c.city)}",
    social: [],
  },

  seo: {
    description: "${esc(c.nameEn)} — ${esc(c.role.en)}. Book your appointment today.",
    descriptionAr: "${esc(c.name.ar)} — ${esc(c.role.ar)}. احجز موعدك اليوم.",
    keywords: ["dentist ${esc(c.city)}", "cosmetic dentist", "${esc(c.nameEn)}", "طبيب اسنان", "تجميل الأسنان"],
  },

  dbFile: "${c.slug}.db",
};
`;
}

function regenerateRegistry() {
  const files = fs
    .readdirSync(CLINICS_SRC)
    .filter((f) => f.endsWith(".ts") && !["types.ts", "index.ts", "registry.generated.ts"].includes(f))
    .map((f) => f.replace(/\.ts$/, ""))
    .sort();
  const imports = files.map((s) => `import { ${s} } from "./${s}";`).join("\n");
  const entries = files.map((s) => `  ${s},`).join("\n");
  const body = `// AUTO-GENERATED by scripts/new-clinic.mjs — do not edit by hand.
// Maps each clinic slug to its config. Regenerated whenever a clinic is added.
import type { ClinicConfig } from "./types";
${imports}

export const clinics: Record<string, ClinicConfig> = {
${entries}
};
`;
  fs.writeFileSync(path.join(CLINICS_SRC, "registry.generated.ts"), body);
  return files;
}

function envTemplate(c) {
  return `# Env for clinic "${c.slug}" (${c.nameEn}). Copy these into the deployment host.
NEXT_PUBLIC_CLINIC="${c.slug}"
DATABASE_URL="file:./${c.slug}.db"
NEXT_PUBLIC_SITE_URL="https://your-domain.example"
APP_URL="https://your-domain.example"

# Auth + worker secrets (generated — keep private)
AUTH_SECRET="${secret(48)}"
WA_AGENT_SECRET="${secret(48)}"

# WhatsApp
WHATSAPP_PROVIDER="waweb"
WHATSAPP_DEFAULT_CC="20"
NEXT_PUBLIC_CLINIC_WHATSAPP="${c.whatsapp}"
`;
}

function deployReadme(c) {
  return `# Deploy — ${c.nameEn} (${c.slug})

This clinic runs the shared app with its own branding, database and WhatsApp number.

## What makes it this clinic
- Branding/config: \`src/lib/clinics/${c.slug}.ts\` (registered in registry.generated.ts)
- Selected by env: \`NEXT_PUBLIC_CLINIC=${c.slug}\`
- Own database: \`DATABASE_URL="file:./${c.slug}.db"\`
- Hero photo: place the image at \`public${c.photo}\` (drop it in \`clinics/${c.slug}/assets/\` too for safekeeping)

## Produce a standalone deployable folder
\`\`\`
node scripts/export-clinic.mjs ${c.slug}
\`\`\`
That creates \`deploy/${c.slug}/\` — a self-contained Next.js app. On the host:
\`\`\`
cd deploy/${c.slug}
npm install
npx prisma migrate deploy
npm run build
npm start
\`\`\`

## Env
Use \`clinics/${c.slug}/.env\` (secrets already generated). Point the domain vars at the real host.
`;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const interactive = Object.keys(args).length === 0;
  let rl;
  const get = async (key, q, def = "") => {
    if (args[key] != null) return args[key];
    if (!rl) rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    return ask(rl, q, def);
  };

  const nameEn = await get("name-en", "Doctor/clinic name (EN)", "Dr. New Clinic");
  const nameAr = await get("name-ar", "Doctor/clinic name (AR)", nameEn);
  const slug = slugify(args.slug || (await get("slug", "URL slug", slugify(nameEn))));
  if (!slug) throw new Error("slug is required");

  const configPath = path.join(CLINICS_SRC, `${slug}.ts`);
  if (fs.existsSync(configPath) && !args.force) {
    throw new Error(`clinic "${slug}" already exists (src/lib/clinics/${slug}.ts). Use --force to overwrite.`);
  }

  const brandEn = await get("brand-en", "Short brand (EN)", nameEn);
  const brandAr = await get("brand-ar", "Short brand (AR)", nameAr);
  const roleEn = await get("role-en", "Role/specialty (EN)", "Cosmetic Dentist");
  const roleAr = await get("role-ar", "Role/specialty (AR)", "طبيب تجميل الأسنان");
  const whatsapp = (await get("whatsapp", "WhatsApp number (digits only, e.g. 2010...)", "")).replace(/\D/g, "");
  const phone = await get("phone", "Phone (display)", whatsapp ? `+${whatsapp}` : "");
  const email = await get("email", "Email", `info@${slug}.clinic`);
  const city = await get("city", "City", "Cairo");
  const photo = await get("photo", "Hero photo file (in public/)", "doctor-placeholder.png");
  if (rl) rl.close();

  const c = {
    slug,
    nameEn,
    name: { en: nameEn, ar: nameAr },
    brand: { en: brandEn, ar: brandAr },
    role: { en: roleEn, ar: roleAr },
    badge: { en: `100% Patient Recommended · ${roleEn}`, ar: `يوصي به ١٠٠٪ من المرضى · ${roleAr}` },
    subtitle: {
      en: `${roleEn} crafting natural, confident smiles — veneers, implants and complete smile makeovers.`,
      ar: `${roleAr} — نصمّم لك ابتسامة طبيعية وواثقة بالعدسات والزراعة وتجميل الابتسامة الكامل.`,
    },
    bio1: {
      en: `${nameEn} is a ${roleEn.toLowerCase()} dedicated to crafting natural, confident smiles — from veneers and smile design to implants and full-mouth rehabilitation.`,
      ar: `${nameAr} ${roleAr}، متخصص في تصميم الابتسامات الطبيعية والواثقة — من العدسات وتصميم الابتسامة إلى الزراعة وإعادة تأهيل الفم بالكامل.`,
    },
    photo: photo.startsWith("/") ? photo : `/${photo}`,
    whatsapp,
    phone,
    email,
    city,
    primary: "#a87f2b",
    primaryDark: "#876419",
    accent: "#d9b659",
  };

  // 1) config
  fs.writeFileSync(configPath, configTemplate(c));
  // 2) registry
  const all = regenerateRegistry();
  // 3) per-clinic folder
  const folder = path.join(ROOT, "clinics", slug);
  fs.mkdirSync(path.join(folder, "assets"), { recursive: true });
  fs.writeFileSync(path.join(folder, ".env"), envTemplate(c));
  fs.writeFileSync(path.join(folder, "DEPLOY.md"), deployReadme(c));
  fs.writeFileSync(path.join(folder, "clinic.json"), JSON.stringify(c, null, 2));

  console.log(`\n✅ Created clinic "${slug}" (${nameEn})`);
  console.log(`   • src/lib/clinics/${slug}.ts`);
  console.log(`   • registry now has: ${all.join(", ")}`);
  console.log(`   • clinics/${slug}/ (.env, DEPLOY.md, assets/)`);
  console.log(`\nNext:`);
  console.log(`   1. Put the hero photo at public${c.photo}`);
  console.log(`   2. Preview:  set NEXT_PUBLIC_CLINIC=${slug} && npm run dev`);
  console.log(`   3. Export:   node scripts/export-clinic.mjs ${slug}\n`);
}

main().catch((e) => {
  console.error("ERROR:", e.message);
  process.exit(1);
});
